name: Release
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.spec.ts'
      - '**.spec.tsx'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/release.yml'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  deploy:
    # Skip deploy if commit message contains "[skip]" or "skip cd" or "cd skip"
    if: ${{ !contains(github.event.head_commit.message, '[skip]') && !contains(github.event.head_commit.message, 'skip cd') && !contains(github.event.head_commit.message, 'cd skip') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Wait on all checks
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: 'deploy'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build
        env:
          VITE_INFURA_PROJECT_ID: ${{ secrets.VITE_INFURA_PROJECT_ID }}

      - name: Push to cf-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: cf-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
