name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'src/**'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'src/**'
      - 'yarn.lock'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: 'bash'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
      - run: yarn install --immutable

      - run: yarn test
